#ifndef LAPLACE_CONFIG_H
#define LAPLACE_CONFIG_H

#include <stddef.h>

#ifndef LAPLACE_DEBUG
#define LAPLACE_DEBUG 0
#endif

#if defined(_WIN32)
#define LAPLACE_PLATFORM_WINDOWS 1
#else
#define LAPLACE_PLATFORM_WINDOWS 0
#endif

#if defined(__clang__)
#define LAPLACE_COMPILER_CLANG 1
#else
#define LAPLACE_COMPILER_CLANG 0
#endif

#define LAPLACE_BUILD_DEBUG ((LAPLACE_DEBUG) != 0)
#define LAPLACE_BUILD_RELEASE ((LAPLACE_DEBUG) == 0)
#define LAPLACE_CACHELINE_BYTES ((size_t)64u)

#define LAPLACE_HV_BACKEND_SCALAR 0
#define LAPLACE_HV_BACKEND_ISPC   1

#ifndef LAPLACE_HV_BACKEND
#define LAPLACE_HV_BACKEND LAPLACE_HV_BACKEND_SCALAR
#endif

#ifndef LAPLACE_HV_OP_BIND_USE_ISPC
#define LAPLACE_HV_OP_BIND_USE_ISPC 1
#endif

#ifndef LAPLACE_HV_OP_XOR_POPCOUNT_USE_ISPC
#define LAPLACE_HV_OP_XOR_POPCOUNT_USE_ISPC 1
#endif

#ifndef LAPLACE_HV_OP_POPCOUNT_USE_ISPC
#define LAPLACE_HV_OP_POPCOUNT_USE_ISPC 1
#endif

#endif
